# This is a basic workflow to help you get started with Actions

name: pyopenms-wheels-arm64

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ pyopenms-arm64 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-lnx-arm64:
    # TODO we have to make sure that this container is always updated with a push to contrib
    runs-on: ubuntu-latest
    container: dockcross/manylinux2014-aarch64

    steps:
    # Cancels older builds if still running
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'"

    - uses: actions/checkout@v2
      name: Checkout sources
      with:
        path: OpenMS
        submodules: contrib

    - name: Build on manylinux2014 for arm64
      run: |
            ls -la
            pushd ..
              ls -la
            popd
            mkdir contrib-build
            pushd contrib-build
              cmake -DBUILD_TYPE=ALL $GITHUB_WORKSPACE/OpenMS/contrib
            popd
            
            # fixes some issues with empty pxd files
            rm -rf src/pyOpenMS/pxds/SwathMapMassCorrection.pxd

            # install Python deps
            for PYBIN in /opt/python/cp37*; do
              "$PYBIN/bin/pip" install -U Cython
              "$PYBIN/bin/pip" install -U setuptools
              "$PYBIN/bin/pip" install -U wheel==0.31.1
              "$PYBIN/bin/pip" install -U numpy
              "$PYBIN/bin/pip" install -U nose
              "$PYBIN/bin/pip" install -U autowrap==0.18.1
            done

            mkdir -p $GITHUB_WORKSPACE/data/wheelhouse/
            mkdir -p $GITHUB_WORKSPACE/data/wheelhouse/before_fix/

            LD_OLD_LIBRARY_PATH=$LD_LIBRARY_PATH

            mkdir openms-build
            cd openms-build
            cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/contrib-build/" $GITHUB_WORKSPACE/OpenMS
            make -j4 OpenMS SuperHirn

            # compile and configure OpenMS
            for PYBIN in /opt/python/cp37*; do

              # configure
              cmake -DCMAKE_PREFIX_PATH="/contrib-build/" -DPYOPENMS=On -DPYTHON_EXECUTABLE:FILEPATH=$PYBIN/bin/python $GITHUB_WORKSPACE/OpenMS
              make -j4 pyopenms
              
              pushd pyOpenMS
                # remove the libraries as auditwheel will take care of linked libs
                rm -rf pyopenms/lib*
                rm -rf build/lib*/pyopenms/lib*
                find . -name "pyopenms*.so" -exec rm -rf {} \; # not sure if that works here?! 
                # create wheel without libraries
                "$PYBIN/bin/pip" wheel . -w wheelhouse_tmp
              popd
            done

            # ensure auditwheel can find the libraries
            export LD_LIBRARY_PATH=$LD_OLD_LIBRARY_PATH:`pwd`/lib

            # strip the libraries before repairing
            strip --strip-all lib/libOpenMS.so
            strip --strip-all lib/libOpenSwathAlgo.so
            strip --strip-all lib/libSuperHirn.so
            
            pushd pyOpenMS
              # Bundle stripped plus external shared libraries into the wheels
              for whl in wheelhouse_tmp/pyopenms*.whl; do
                auditwheel repair "$whl" -w wheelhouse/
              done

              # Note: Uncomment this line if you want to test the wheels before our fix
              #/usr/bin/cp wheelhouse/* $GITHUB_WORKSPACE/data/wheelhouse/before_fix/

              # Somehow auditwheel is broken and we get the wrong libraries here for
              # libcrypto and libssl, lets go and fix it ...
              yum install -y zip
              pushd wheelhouse
                for whl in pyopenms*.whl
                do
                  mkdir -p fix
                  cp $whl fix/fix.zip
                  pushd fix
                    unzip fix.zip
                    /usr/bin/cp /lib64/libssl.so.10  pyopenms/.libs/libssl-*
                    /usr/bin/cp /lib64/libcrypto.so.10  pyopenms/.libs/libcrypto-*
                    zip -r ../$whl pyopenms/
                  popd
                  rm -rf fix
                done
              popd
              mv wheelhouse/* $GITHUB_WORKSPACE/data/wheelhouse/
            popd

    - uses: actions/upload-artifact@v1
      name: Upload artifacts
      with:
        name: ${{ runner.os }}-wheels
        path: data/wheelhouse/
